#!/usr/bin/env python3
"""Ops-only mail inject. Bind published to 127.0.0.1. Not on the edge."""
from __future__ import annotations

import os
import re
import smtplib
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

APP_YAML = Path(os.environ.get("APP_YAML", "/app/app.yaml"))
APP_SECRETS = Path(os.environ.get("APP_SECRETS", "/app/app.secrets.yaml"))
USERS = Path(os.environ.get("USERS_FILE", "/data/users.runtime"))
POSTFIX = os.environ.get("POSTFIX_HOST", "postfix")
LISTEN = ("0.0.0.0", int(os.environ.get("PORT", "8080")))


def yaml_map(path: Path, section: str) -> dict[str, str]:
    data: dict[str, str] = {}
    current = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if line.strip() == f"{section}:":
            current = section
            continue
        if current == section and ":" in line:
            key, _, value = line.strip().partition(":")
            data[key.strip()] = value.strip().strip("'").strip('"')
    return data


def token() -> str:
    admin = yaml_map(APP_YAML, "admin")
    if APP_SECRETS.is_file():
        admin = {**admin, **yaml_map(APP_SECRETS, "admin")}
    got = admin.get("token") or admin.get("password")
    if not got:
        raise SystemExit(
            f"missing admin.token in {APP_YAML} or {APP_SECRETS}"
        )
    return got


def localpart(addr: str) -> str:
    addr = addr.split("<", 1)[-1].split(">", 1)[0].strip().lower()
    return addr.split("@", 1)[0]


def recipients(raw: str) -> list[str]:
    head = raw.split("\n\n", 1)[0]
    found: list[str] = []
    for match in re.finditer(r"(?im)^To:\s*(.+?)(?=\n[^\s]|\Z)", head, re.S):
        chunk = re.sub(r"\s+", " ", match.group(1))
        for part in chunk.split(","):
            email = re.search(r"[\w.+-]+@[\w.-]+", part)
            if email:
                found.append(email.group(0).lower())
    return found


def envelope_from(raw: str) -> str:
    head = raw.split("\n\n", 1)[0]
    match = re.search(r"(?im)^From:\s*.*?([\w.+-]+@[\w.-]+)", head)
    return match.group(1) if match else "world@mail.example"


def mailbox() -> dict[str, str]:
    box = yaml_map(APP_YAML, "login")
    if not box.get("username") or not box.get("password"):
        raise SystemExit(f"app.yaml missing login.username / login.password: {APP_YAML}")
    return box


def agent_pass(name: str) -> str | None:
    box = mailbox()
    if name == box["username"]:
        return "{PLAIN}" + box["password"]
    return None


def users_line(name: str, scheme_pass: str) -> str:
    return f"{name}:{scheme_pass}:1000:1000::/srv/vmail/{name}"


def has_user(name: str) -> bool:
    if not USERS.is_file():
        return False
    for raw in USERS.read_text(encoding="utf-8").splitlines():
        if raw.split(":", 1)[0] == name:
            return True
    return False


def write_users(lines: list[str]) -> None:
    # Write in place. os.replace cannot swap a Docker bind-mounted file.
    USERS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    USERS.chmod(0o644)


def existing_user_lines() -> list[str]:
    if not USERS.is_file():
        return []
    return [ln for ln in USERS.read_text(encoding="utf-8").splitlines() if ln and not ln.startswith("#")]


def ensure_agent_users() -> None:
    box = mailbox()
    write_users(
        [
            "# generated by injectd — not for the agent",
            users_line(box["username"], "{PLAIN}" + box["password"]),
        ]
    )


def ensure_recipient(name: str) -> None:
    if has_user(name):
        return
    scheme = agent_pass(name)
    if scheme is None:
        scheme = "{PLAIN}ops-only"
    lines = existing_user_lines()
    lines.append(users_line(name, scheme))
    write_users(lines)


def authorized(handler: BaseHTTPRequestHandler) -> bool:
    header = handler.headers.get("Authorization", "")
    expected = token()
    if header == f"Bearer {expected}":
        return True
    return False


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt: str, *args: object) -> None:
        return

    def do_GET(self) -> None:
        if self.path.rstrip("/") == "/health":
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"ok\n")
            return
        self.send_error(404)

    def do_POST(self) -> None:
        if self.path.rstrip("/") != "/send":
            self.send_error(404)
            return
        if not authorized(self):
            self.send_error(401)
            return
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        ensure_agent_users()
        tos = recipients(raw)
        if not tos:
            self.send_error(400, "To: required")
            return
        for addr in tos:
            ensure_recipient(localpart(addr))
        with smtplib.SMTP(POSTFIX, 25, timeout=30) as smtp:
            smtp.sendmail(envelope_from(raw), tos, raw.encode())
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"sent\n")


def main() -> None:
    token()
    HTTPServer(LISTEN, Handler).serve_forever()


if __name__ == "__main__":
    main()
