#!/usr/bin/env python3
"""Generate per-world runtime keys (gitignored). Not eval credentials.

Writes:
  worlds/<id>/runtime.env
  worlds/<id>/apps/<cms|shop>/.env  (meridian and/or unistore)
  worlds/<id>/apps/mail/.env
  apps/{meridian,mail,unistore}/.env (catalog --catalog only)

Existing files are left unchanged unless --rotate.
"""
from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path


def token(n: int = 32) -> str:
    # Leading letter so values never look like CLI flags.
    return "k" + secrets.token_urlsafe(n)


def write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated per world bake — do not commit", ""]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)


def ensure_mail_inject_secrets(app_dir: Path, *, rotate: bool = False) -> None:
    """Create mail app.secrets.yaml with a random inject token if missing.

    Labs unpack without app.secrets.yaml; injectd bind-mounts this file.
    Shop baker secrets are never auto-generated (must come from rotate-ops).
    """
    secrets_path = app_dir / "app.secrets.yaml"
    if secrets_path.is_file() and not rotate:
        return
    inject = secrets.token_hex(16)
    body = "\n".join(
        [
            "# Ops secrets — inject token for local apply/gate. Not eval credentials.",
            "# Generated by runtime-env/ensure.py when missing. Do not commit.",
            "admin:",
            f"  token: '{inject}'",
            "",
        ]
    )
    secrets_path.write_text(body, encoding="utf-8")
    secrets_path.chmod(0o600)
    print(f"wrote mail inject secrets at {secrets_path} (token not printed)")


def wp_values() -> dict[str, str]:
    return {
        "MYSQL_ROOT_PASSWORD": token(24),
        "MYSQL_PASSWORD": token(24),
        "WORDPRESS_AUTH_KEY": token(48),
        "WORDPRESS_SECURE_AUTH_KEY": token(48),
        "WORDPRESS_LOGGED_IN_KEY": token(48),
        "WORDPRESS_NONCE_KEY": token(48),
        "WORDPRESS_AUTH_SALT": token(48),
        "WORDPRESS_SECURE_AUTH_SALT": token(48),
        "WORDPRESS_LOGGED_IN_SALT": token(48),
        "WORDPRESS_NONCE_SALT": token(48),
    }


def mail_values() -> dict[str, str]:
    return {
        "MYSQL_ROOT_PASSWORD": token(24),
        "MYSQL_PASSWORD": token(24),
        "ROUNDCUBEMAIL_DES_KEY": token(24),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--world",
        default=None,
        help="World id (or set WORLD). Required unless --catalog.",
    )
    ap.add_argument("--catalog", action="store_true", help="apps/meridian, apps/mail, and apps/unistore .env")
    ap.add_argument("--rotate", action="store_true")
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[3]
    sys.path.insert(0, str(root / "scripts" / "common" / "lib"))
    from require_world import require_world

    if args.catalog:
        for rel, values in (
            ("apps/meridian/.env", wp_values()),
            ("apps/mail/.env", mail_values()),
            ("apps/unistore/.env", wp_values()),
        ):
            path = root / rel
            if path.is_file() and not args.rotate:
                print(f"catalog env exists: {path}")
                continue
            write_env(path, values)
            print(f"wrote {rel} (not printed)")
        return

    world_id = require_world(args.world, root=root)
    world = root / "worlds" / world_id
    runtime = world / "runtime.env"

    mail_dir = world / "apps" / "mail"
    if mail_dir.is_dir():
        ensure_mail_inject_secrets(mail_dir, rotate=False)

    if runtime.is_file() and not args.rotate:
        print(f"runtime env exists: {runtime}")
        return

    union: dict[str, str] = {}
    for app_id, prefix, values_fn in (
        ("meridian", "MERIDIAN", wp_values),
        ("unistore", "UNISTORE", wp_values),
        ("mail", "MAIL", mail_values),
    ):
        app_dir = world / "apps" / app_id
        if not app_dir.is_dir():
            continue
        values = values_fn()
        write_env(app_dir / ".env", values)
        union.update({f"{prefix}_{k}": v for k, v in values.items()})

    if not union:
        raise SystemExit(f"no apps under {world / 'apps'}")
    write_env(runtime, union)
    print(f"wrote runtime env for {world_id} (not printed)")


if __name__ == "__main__":
    main()
